config/routes.rb
Rails.application.routes.draw do
   resources :labels, only: [:show]

   resources :topics do
     resources :posts, except: [:index]
  end

  resources :posts, only: [] do
    resources :comments, only: [:create, :destroy]
    resources :favorites, only: [:create, :destroy]

  post '/up-vote' => 'votes#up_vote', as: :up_vote
  post '/down-vote' => 'votes#down_vote', as: :down_vote
  end

  resources :users, only: [:new, :create, :show]

  resources :sessions, only: [:new, :create, :destroy]

  get 'about' => 'welcome#about'
  get 'learn_more' => 'welcome#learn_more'

  root 'welcome#index'

  namespace :api do
     namespace :v1 do
       resources :users, only: [:index, :show, :create, :update]
       resources :topics, except: [:edit, :new]
     end
   end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end

  def learn_more
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/about.html.erb
<div class="about-page">
  <h1>About Bulletin</h1>
  <p>Bulletin is resource that allows anyone to browse, share, and discuss topics and posts.
  <p>Bulletin was a project aimed to teach and learn the fundamentals of web developement for beginners.</p>
  <p>Created by: Matt</p>
</div>

app/views/welcome/index.html.erb
<% provide(:nav_style, "transparent-nav") %>

<div class="home-img">
  <h1>Discuss anything and everything</h1>
  <h5>Bulletin is a resource for discussing topics and sharing links with the community or your friends</h5>
  <p><%= link_to "Learn More", learn_more_path, class: "btn btn-primary"%></p>
</div>

<section class="container col-info">
  <div class="col-sm-4">
    <%= image_tag("image1.png") %>
    <h3>Discuss</h3>
    <p>Start a new topic or join an existing one. Discuss latest news, projects, or stories with friends and the Bulletin community.</p>
  </div>

  <div class="col-sm-4">
    <%= image_tag("image2.png") %>
    <h3>Share Links</h3>
    <p>Spread the word. Share your favorite links and see what others have to say about it, or see what the community has shared.</p>
  </div>
  
  <div class="col-sm-4">
    <%= image_tag("image3.png") %>
    <h3>Easy to Use</h3>
    <p>Once you make an account your ready to share, like, and discuss with everyone all over the world.</p>
  </div>
</section>

app/views/welcome/learn_more.html.erb
<div class="learn-img">
  <section class="learn-content">
    <h1>How to use Bulletin</h1>
    <div>
      <h2>1: Step One</h2>
      <p>
        Sign up for an account. Take a look at the top right corner and select <strong>Log In</strong> if you already have an account, or <strong>Sign Up</strong> if you don't have one yet.
        Creating an account is quick and simple. Just add a valid email address, your unique username, and a password and your all good to go.
      </p>
    </div>

    <div>
      <h2>2: Step Two</h2>
      <p>
        Bulletin offers a wide range of topics and posts for you to browse and take part of the discussion. Navigate to the <strong>Topics</strong> tab at the top of the page. This will take
        you to Bulletin's list of available Topics. Select any topic you like.<br><br> Once you have chosen a topic, you can selct any post under that topic to take part in. See what the community has
        to say or comment your own views. Like or hate a post? Just hit the <strong>Up Vote</strong> or <strong>Down Vote</strong> buttons to like or dislike a post.
      </p>
    </div>

    <div>
      <h2>3: Step Three</h2>
      <p>
        Start your own discussion! Have a project to discuss with friends? Have a news story you want to share? Have a funny link you want people to see? Share it! Under the <strong>Topics</strong> page
        you'll see the <strong>New Topic</strong> icon. Just click on it and your ready to share.<br><br> Want to start a new post on an existing topic? Just click on the <strong>New Post</strong> icon to get started.
        Topics and posts must follow Bulletin guidelines. Topics and posts violating guidelines will be removed.
      </p>
    </div>
  </section>
</div>