config/routes.rb
Rails.application.routes.draw do
   resources :labels, only: [:show]

   resources :topics do
     resources :posts, except: [:index]
  end

  resources :posts, only: [] do
    resources :comments, only: [:create, :destroy]
    resources :favorites, only: [:create, :destroy]

  post '/up-vote' => 'votes#up_vote', as: :up_vote
  post '/down-vote' => 'votes#down_vote', as: :down_vote
  end

  resources :users, only: [:new, :create, :show]

  resources :sessions, only: [:new, :create, :destroy]

  get 'about' => 'welcome#about'
  get 'learn_more' => 'welcome#learn_more'

  root 'welcome#index'

  namespace :api do
     namespace :v1 do
       resources :users, only: [:index, :show, :create, :update]
       resources :topics, except: [:edit, :new]
     end
   end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user

  validates :body, presence: true
  validates :user, presence: true

  after_create :send_favorite_emails

  default_scope { order('updated_at DESC') }
  end

  private

  def send_favorite_emails
    post.favorites.each do |favorite|
    FavoriteMailer.new_comment(favorite.user, post, self).deliver_now
  end
end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
end

app/models/label.rb
class Label < ActiveRecord::Base
  has_many :labelings
  has_many :topics, through: :labelings, source: :labelable, source_type: :Topic
  has_many :posts, through: :labelings, source: :labelable, source_type: :Post

  def self.update_labels(label_string)
    return Label.none if label_string.blank?

    label_string.split(",").map do |label|
      Label.find_or_create_by(name: label.strip)
    end
  end
end

app/models/labeling.rb
class Labeling < ActiveRecord::Base
   belongs_to :labelable, polymorphic: true
   belongs_to :label
 end

app/models/post.rb
class Post < ActiveRecord::Base
    belongs_to :topic
    belongs_to :user
    has_many :comments, dependent: :destroy
    has_many :votes, dependent: :destroy
    has_many :labelings, as: :labelable
    has_many :labels, through: :labelings
    has_many :favorites, dependent: :destroy

    default_scope { order('rank DESC') }

    scope :visible_to, -> (user) { user ? all : joins(:topic).where('topics.public' => true) }

    validates :title, length: { minimum: 5 }, presence: true
    validates :body, length: { minimum: 20 }, presence: true
    validates :topic, presence: true
    validates :user, presence: true

    def up_votes
      votes.where(value: 1).count
    end

    def down_votes
      votes.where(value: -1).count
    end

    def points
      votes.sum(:value)
    end

    def update_rank
      age_in_days = (created_at - Time.new(1970,1,1)) / 1.day.seconds
      new_rank = points + age_in_days
      update_attribute(:rank, new_rank)
    end
end

app/models/topic.rb
class Topic < ActiveRecord::Base
    belongs_to :user
    has_many :posts, dependent: :destroy
    has_many :labelings, as: :labelable
    has_many :labels, through: :labelings

    scope :visible_to, -> (user) { user ? all : where(public: true) }

    validates :name, presence: true
    validates :description, length: { minimum: 20 }, presence: true

    def self.search(search)
        where("name ILIKE ? OR description ILIKE ?", "%#{search}%", "%#{search}%")
    end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :topics, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :votes, dependent: :destroy
  has_many :favorites, dependent: :destroy

  before_save { self.email = email.downcase }
  before_save { self.role ||= :member }

  before_create :generate_auth_token

  validates :name, length: { minimum: 1, maximum: 100 }, presence: true
  validates :password, presence: true, length: { minimum: 6 }, if: "password_digest.nil?"
  validates :password, length: { minimum: 6 }, allow_blank: true
  validates :email,
            presence: true,
            uniqueness: { case_sensitive: false },
            length: { minimum: 3, maximum: 254 }

  has_secure_password

  enum role: [:member, :admin]

  def favorite_for(post)
    favorites.where(post_id: post.id).first
  end

  def avatar_url(size)
    gravatar_id = Digest::MD5::hexdigest(self.email).downcase
    "http://gravatar.com/avatar/#{gravatar_id}.png?s=#{size}"
  end

  def generate_auth_token
   loop do
     self.auth_token = SecureRandom.base64(64)
     break unless User.find_by(auth_token: auth_token)
   end
 end
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
  after_save :update_post

  validates :value, inclusion: { in: [-1, 1], message: "%{value} is not a valid vote." }, presence: true

  private

  def update_post
    post.update_rank
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :require_sign_in, except: :show

  before_action :authorize_user, except: [:show, :new, :create]

  def show
     @post = Post.find(params[:id])
  end

  def new
    @topic = Topic.find(params[:topic_id])
    @post = Post.new
  end

  def create
    @topic = Topic.find(params[:topic_id])
    @post = @topic.posts.build(post_params)
    @post.user = current_user

    if @post.save
       @post.labels = Label.update_labels(params[:post][:labels])
       flash[:notice] = "Post was saved."
      redirect_to [@topic, @post]
    else

      flash.now[:alert] = "There was an error saving the post. Please try again."
      render :new
    end
  end

  def edit
     @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    @post.assign_attributes(post_params)

    if @post.save
       @post.labels = Label.update_labels(params[:post][:labels])
      flash[:notice] = "Post was updated."
      redirect_to [@post.topic, @post]
    else
      flash.now[:alert] = "There was an error saving the post. Please try again."
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])

    if @post.destroy
      flash[:notice] = "\"#{@post.title}\" was deleted successfully."
      redirect_to @post.topic
    else
      flash.now[:alert] = "There was an error deleting the post."
      render :show
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :body)
  end

  def authorize_user
    post = Post.find(params[:id])
    unless current_user == post.user || current_user.admin?
      flash[:alert] = "You must be an admin to do that."
      redirect_to [post.topic, post]
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts.visible_to(current_user)
  end

  def create
    @user = User.new
    @user.name = params[:user][:name]
    @user.email = params[:user][:email]
    @user.password = params[:user][:password]
    @user.password_confirmation = params[:user][:password_confirmation]

    if @user.save
      flash[:notice] = "Welcome to Bulletin #{@user.name}!"
      create_session(@user)
      redirect_to root_path
    else
      flash.now[:alert] = "There was an error creating your account. Please try again."
      render :new
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def form_group_tag(errors, &block)
    css_class = 'form-group'
    css_class << ' has-error' if errors.any?

    content_tag :div, capture(&block), class: css_class
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
  def user_is_authorized_for_comment?(comment)
      current_user && (current_user == comment.user || current_user.admin?)
   end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/labels_helper.rb
module LabelsHelper
    def labels_to_buttons(labels)
      raw labels.map { |l| link_to l.name, label_path(id: l.id), class: 'btn-xs btn-primary' }.join(' ')
  end
end

app/helpers/posts_helper.rb
module PostsHelper
  
  def user_is_authorized_for_post?(post)
       current_user && (current_user == post.user || current_user.admin?)
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def create_session(user)
    session[:user_id] = user.id
  end

  def destroy_session(user)
    session[:user_id] = nil
  end

  def current_user
    User.find_by(id: session[:user_id])
  end
end

app/helpers/topics_helper.rb
module TopicsHelper
  def user_is_authorized_for_topics?
      current_user.nil? == false
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
    <ul>
      <li><%= link_to "About Us", about_path %></li>
      <li>Copyright <i class="fa fa-copyright" aria-hidden="true"></i> 2017 Bulletin</li>
    </ul>
  </nav>
</footer>

app/views/layouts/_guidelines.html.erb
<div class="guidelines">
  <ul>
    <li>Make sure the topic is appropriate.</li>
    <li>No topics containing violence or dangerous content.</li>
    <li>Sexual content is prohibited.</li>
    <li>No spam or misleading topics.</li>
  </ul>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar <%= yield(:nav_style) %>">
  <a class="mobile-nav glyphicon glyphicon-th-list"></a>
  <%= link_to image_tag("logo.png"), root_path %>
  <ul class="main-nav">
    <%= link_to "Topics", topics_path %>
    <%= link_to "About", about_path %>
    <%= link_to "Share", new_topic_path %>
    <div class="user-info">
      <% if current_user %>
        <li class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><%=image_tag current_user.avatar_url(48), class: "gravatar" %></li>
        <ul class="dropdown-menu pull-right">
         <li><%= link_to current_user.name, user_path(current_user) %></li>
         <li><%= link_to "Sign Out", session_path(current_user), method: :delete %></li>
       </ul>
        <% else %>
        <div>
          <%= link_to "Log In", new_session_path, class: 'btn '%>
          <%= link_to "Sign Up", new_user_path, class: 'btn' %>
        </div>
        <% end %>
    </div>
    <div class="search-bar">
      <%= form_tag(topics_path, :method => "get", id: "search-form") do %>
        <%= text_field_tag :search, params[:search], placeholder: "Search" %>
        <%= submit_tag "Search", :name => nil, class: 'btn btn-default' %>
      <% end %>
    </div>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bulletin</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>
  <div>
    <% if flash[:notice] %>
       <div class="alert-wrapper">
         <button type="button" class="close" data-dismiss="alert">&times;</button>
         <%= flash[:notice] %>
       </div>
     <% elsif flash[:error] %>
       <div class="alert-wrapper">
         <button type="button" class="close" data-dismiss="alert">&times;</button>
         <%= flash[:error] %>
       </div>
     <% elsif flash[:alert] %>
       <div class="alert-wrapper">
         <button type="button" class="close" data-dismiss="alert">&times;</button>
         <%= flash[:alert] %>
       </div>
     <% end %>
   </div>
  <%= yield %>

  <%= render 'layouts/footer' %>
</body>
</html>